import { StyleSheet } from "react-native";

import { control, radii, spacing, typography } from "@/theme";
import type { ThemeColors } from "@/theme/tokens";

export const createInventoryImportStyles = (colors: ThemeColors) => StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background.app },
  screen: { flex: 1 },
  content: {
    gap: spacing[4],
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    paddingHorizontal: spacing[4],
    paddingTop: spacing[4],
    paddingBottom: spacing[8],
  },
  header: { flexDirection: "row", alignItems: "center", gap: spacing[3] },
  headerCopy: { minWidth: 0, flex: 1, gap: spacing[1] },
  title: { ...typography.h2, color: colors.text.primary },
  subtitle: { ...typography.bodySmall, color: colors.text.secondary },
  storeContext: {
    minHeight: control.lg,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    paddingHorizontal: spacing[3],
    borderWidth: 1,
    borderColor: colors.primary[200],
    borderRadius: radii.lg,
    backgroundColor: colors.primary[50],
  },
  storeCopy: { minWidth: 0, flex: 1, gap: 1 },
  storeCaption: { ...typography.caption, color: colors.text.secondary },
  storeName: { ...typography.label, color: colors.text.primary },
  stepper: { flexDirection: "row", alignItems: "flex-start", paddingHorizontal: spacing[2] },
  stepItem: { minWidth: 0, flex: 1, alignItems: "center", position: "relative", gap: spacing[1] },
  stepDot: { width: 26, height: 26, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.border.strong, borderRadius: radii.full, backgroundColor: colors.background.surface, zIndex: 1 },
  stepDotActive: { borderColor: colors.primary[600], backgroundColor: colors.primary[600] },
  stepNumber: { ...typography.caption, color: colors.text.secondary, fontWeight: "700" },
  stepNumberActive: { color: colors.text.onPrimary },
  stepLabel: { ...typography.caption, color: colors.text.muted },
  stepLabelActive: { color: colors.primary[700], fontWeight: "600" },
  stepLine: { position: "absolute", top: 12, left: "50%", width: "100%", height: 1, backgroundColor: colors.border.default },
  stepLineActive: { backgroundColor: colors.primary[600] },
  emptyContent: { gap: spacing[4] },
  pickerCard: { alignItems: "center", gap: spacing[3], paddingVertical: spacing[8] },
  pickerIcon: { width: 56, height: 56, alignItems: "center", justifyContent: "center", borderRadius: radii.full, backgroundColor: colors.primary[50] },
  pickerTitle: { ...typography.h3, color: colors.text.primary, textAlign: "center" },
  pickerCopy: { ...typography.bodySmall, color: colors.text.secondary, textAlign: "center" },
  fullButton: { alignSelf: "stretch" },
  supported: { ...typography.caption, color: colors.text.muted, textAlign: "center" },
  reassurance: { ...typography.bodySmall, color: colors.text.secondary, textAlign: "center", paddingHorizontal: spacing[5] },
  fileCard: { gap: spacing[3] },
  fileHeading: { flexDirection: "row", alignItems: "center", gap: spacing[3] },
  fileIcon: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: radii.md, backgroundColor: colors.primary[50] },
  fileCopy: { minWidth: 0, flex: 1, gap: spacing[1] },
  fileName: { ...typography.label, color: colors.text.primary },
  fileMeta: { ...typography.caption, color: colors.text.secondary },
  detected: { ...typography.label, color: colors.semantic.success },
  processingRow: { flexDirection: "row", alignItems: "center", gap: spacing[2] },
  processingText: { ...typography.bodySmall, color: colors.text.secondary },
  fileActions: { flexDirection: "row", gap: spacing[2] },
  flexButton: { minWidth: 0, flex: 1 },
  parsingBlock: { alignItems: "center", gap: spacing[2], paddingVertical: spacing[5] },
  parsingTitle: { ...typography.title, color: colors.text.primary, textAlign: "center" },
  copy: { ...typography.bodySmall, color: colors.text.secondary },
  sectionGap: { gap: spacing[3] },
  mappingIntro: { gap: spacing[1] },
  sectionTitle: { ...typography.title, color: colors.text.primary },
  mappingCard: { gap: 0, padding: 0, overflow: "hidden" },
  mappingRow: { minHeight: 58, flexDirection: "row", alignItems: "center", gap: spacing[2], paddingHorizontal: spacing[3], borderBottomWidth: 1, borderBottomColor: colors.border.default },
  mappingSource: { ...typography.bodySmall, minWidth: 0, flex: 1, color: colors.text.primary },
  mappingArrow: { ...typography.bodySmall, color: colors.text.muted },
  mappingSelect: { minWidth: 136, maxWidth: "52%", minHeight: control.md, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing[2], paddingHorizontal: spacing[2], borderWidth: 1, borderColor: colors.border.default, borderRadius: radii.md },
  mappingSelectText: { ...typography.caption, minWidth: 0, flex: 1, color: colors.text.primary },
  error: { ...typography.bodySmall, color: colors.semantic.danger },
  summaryCard: { gap: spacing[2] },
  summaryDetected: { ...typography.bodySmall, color: colors.text.secondary },
  summaryGrid: { flexDirection: "row", gap: spacing[2] },
  summaryValue: { minWidth: 0, flex: 1, gap: spacing[1], padding: spacing[2], borderRadius: radii.md, backgroundColor: colors.background.subtle },
  summaryNumber: { ...typography.h3 },
  summaryLabel: { ...typography.caption, color: colors.text.secondary },
  previewHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing[2] },
  searchBox: { minHeight: control.md, flexDirection: "row", alignItems: "center", gap: spacing[2], paddingHorizontal: spacing[3], borderWidth: 1, borderColor: colors.border.default, borderRadius: radii.md, backgroundColor: colors.background.surface },
  searchInput: { ...typography.bodySmall, minWidth: 0, flex: 1, color: colors.text.primary },
  filterRow: { gap: spacing[2] },
  filterChip: { minHeight: control.sm, justifyContent: "center", paddingHorizontal: spacing[3], borderWidth: 1, borderColor: colors.border.default, borderRadius: radii.full },
  filterChipActive: { borderColor: colors.primary[200], backgroundColor: colors.primary[50] },
  filterLabel: { ...typography.caption, color: colors.text.secondary },
  filterLabelActive: { color: colors.primary[700], fontWeight: "600" },
  previewList: { gap: spacing[2] },
  productCard: { gap: 0, padding: 0, overflow: "hidden" },
  productHeader: { minHeight: 88, flexDirection: "row", alignItems: "center", gap: spacing[2], padding: spacing[3] },
  productCopy: { minWidth: 0, flex: 1, gap: spacing[1] },
  productName: { ...typography.label, color: colors.text.primary },
  productSummary: { ...typography.caption, color: colors.text.secondary },
  productSku: { ...typography.caption, color: colors.text.muted },
  productMatch: { ...typography.caption, color: colors.primary[700] },
  productEnd: { alignItems: "flex-end", gap: spacing[2] },
  productDetail: { gap: spacing[1], padding: spacing[3], borderTopWidth: 1, borderTopColor: colors.border.default, backgroundColor: colors.background.subtle },
  detailLine: { ...typography.caption, color: colors.text.secondary },
  matchLine: { ...typography.caption, color: colors.primary[700], fontWeight: "600" },
  issueLine: { ...typography.caption, color: colors.semantic.danger },
  editButton: { alignSelf: "flex-start", marginTop: spacing[1] },
  statusChip: { minHeight: 24, flexDirection: "row", alignItems: "center", gap: spacing[1], paddingHorizontal: spacing[2], borderRadius: radii.full },
  statusLabel: { ...typography.caption, fontWeight: "600" },
  previewActions: { flexDirection: "row", gap: spacing[2], paddingTop: spacing[1] },
  importingBlock: { alignItems: "center", gap: spacing[2], paddingVertical: spacing[8] },
  progressTrack: { width: "100%", height: 7, overflow: "hidden", borderRadius: radii.full, backgroundColor: colors.gray[100] },
  progressFill: { height: "100%", borderRadius: radii.full, backgroundColor: colors.primary[600] },
  resultCard: { alignItems: "center", gap: spacing[3], paddingVertical: spacing[6] },
  failureCard: { alignItems: "center", gap: spacing[3], paddingVertical: spacing[6], borderColor: colors.semantic.dangerBackground },
  resultTitle: { ...typography.h3, color: colors.text.primary, textAlign: "center" },
  resultCopy: { ...typography.bodySmall, color: colors.text.secondary, textAlign: "center" },
  resultActions: { alignSelf: "stretch", flexDirection: "row", gap: spacing[2], marginTop: spacing[1] },
  overlay: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(15, 23, 42, 0.32)" },
  sheet: { gap: spacing[3], padding: spacing[4], borderTopLeftRadius: radii.xl, borderTopRightRadius: radii.xl, backgroundColor: colors.background.surface },
  editorSheet: { maxHeight: "92%", gap: spacing[3], padding: spacing[4], borderTopLeftRadius: radii.xl, borderTopRightRadius: radii.xl, backgroundColor: colors.background.surface },
  sheetHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing[3] },
  sheetTitle: { ...typography.h3, minWidth: 0, flex: 1, color: colors.text.primary },
  sheetCopy: { ...typography.bodySmall, color: colors.text.secondary },
  storeOption: { minHeight: control.lg, flexDirection: "row", alignItems: "center", gap: spacing[3], paddingHorizontal: spacing[2], borderRadius: radii.md },
  storeOptionActive: { backgroundColor: colors.primary[50] },
  storeOptionLabel: { ...typography.bodySmall, minWidth: 0, flex: 1, color: colors.text.primary },
  storeOptionLabelActive: { color: colors.primary[700], fontWeight: "600" },
  mappingMenu: { margin: spacing[5], borderRadius: radii.lg, backgroundColor: colors.background.surface },
  mappingOption: { minHeight: control.lg, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing[3], paddingHorizontal: spacing[4], borderBottomWidth: 1, borderBottomColor: colors.border.default },
  mappingOptionLabel: { ...typography.bodySmall, color: colors.text.primary },
  editorContent: { gap: spacing[3], paddingBottom: spacing[2] },
  field: { gap: spacing[1] },
  fieldLabel: { ...typography.label, color: colors.text.primary },
  fieldInput: { ...typography.bodySmall, minHeight: control.md, paddingHorizontal: spacing[3], borderWidth: 1, borderColor: colors.border.default, borderRadius: radii.md, color: colors.text.primary, backgroundColor: colors.background.surface },
  matchCard: { gap: spacing[2], backgroundColor: colors.semantic.warningBackground, borderColor: colors.semantic.warningBackground },
  matchTitle: { ...typography.label, color: colors.text.primary },
  editorActions: { flexDirection: "row", gap: spacing[2] },
  dialogOverlay: { flex: 1, alignItems: "center", justifyContent: "center", padding: spacing[5], backgroundColor: "rgba(15, 23, 42, 0.32)" },
  dialog: { width: "100%", maxWidth: 440, gap: spacing[3] },
  dialogTitle: { ...typography.h3, color: colors.text.primary },
  dialogActions: { flexDirection: "row", gap: spacing[2], marginTop: spacing[1] },
  pressed: { opacity: 0.74 },
  disabled: { opacity: 0.6 },
});
