import { StyleSheet } from "react-native";

import { control, radii, spacing, typography } from "@/theme";
import type { ThemeColors } from "@/theme/tokens";

export const controlHeight = 40;

export const createInsightsStyles = (colors: ThemeColors) => StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background.app }, screen: { flex: 1 }, scroll: { flex: 1 },
  content: { flexGrow: 1, gap: spacing[4], width: "100%", maxWidth: 760, alignSelf: "center", paddingHorizontal: spacing[4], paddingTop: spacing[4], paddingBottom: spacing[8] },
  headerActions: { flexDirection: "row", alignItems: "center", gap: spacing[1] },
  tabs: { minHeight: 46, flexDirection: "row", padding: spacing[1], borderRadius: radii.md, backgroundColor: colors.background.subtle, borderWidth: 1, borderColor: colors.border.default },
  tab: { minHeight: 38, flex: 1, alignItems: "center", justifyContent: "center", borderRadius: radii.sm },
  tabActive: { backgroundColor: colors.background.surface, borderWidth: 1, borderColor: colors.border.default }, tabLabel: { ...typography.label, color: colors.text.secondary }, tabLabelActive: { color: colors.primary[600], fontWeight: "600" },
  row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing[3] }, section: { gap: spacing[3] }, sectionTitle: { ...typography.title, color: colors.text.primary }, sectionSubtitle: { ...typography.bodySmall, color: colors.text.secondary }, card: { gap: spacing[3] }, cardTitle: { ...typography.label, color: colors.text.primary }, caption: { ...typography.caption, color: colors.text.secondary },
  periodButton: { minHeight: controlHeight, flexDirection: "row", alignItems: "center", gap: spacing[2], paddingHorizontal: spacing[3], borderWidth: 1, borderColor: colors.border.default, borderRadius: radii.md, backgroundColor: colors.background.surface }, periodLabel: { ...typography.label, color: colors.text.primary, maxWidth: 136 },
  totalCard: { padding: spacing[5], gap: spacing[2] }, totalLabel: { ...typography.label, color: colors.text.secondary }, totalValue: { fontSize: 36, lineHeight: 42, fontWeight: "700", color: colors.text.primary }, totalFoot: { ...typography.bodySmall, color: colors.text.muted },
  statusGrid: { flexDirection: "row", gap: spacing[2] }, statusCard: { minHeight: 92, flex: 1, padding: spacing[3], justifyContent: "space-between", gap: spacing[2] }, statusTop: { flexDirection: "row", alignItems: "center", gap: spacing[1] }, statusDot: { width: 8, height: 8, borderRadius: radii.full }, statusLabel: { ...typography.caption, color: colors.text.secondary, flexShrink: 1 }, statusCount: { ...typography.h3, color: colors.text.primary },
  comparisonLabel: { ...typography.caption, color: colors.text.muted }, comparisonGrid: { flexDirection: "row", gap: spacing[2] }, comparisonTile: { flex: 1, minWidth: 0, padding: spacing[3], borderRadius: radii.md, backgroundColor: colors.background.subtle, gap: spacing[1] }, comparisonName: { ...typography.caption, color: colors.text.secondary }, comparisonValue: { ...typography.title, color: colors.text.primary }, comparisonChange: { ...typography.caption, color: colors.text.muted }, comparisonNote: { ...typography.caption, color: colors.text.secondary, lineHeight: 18 },
  findingRow: { flexDirection: "row", alignItems: "flex-start", gap: spacing[2] }, findingBullet: { width: 7, height: 7, borderRadius: radii.full, marginTop: 6, backgroundColor: colors.primary[500] }, findingText: { ...typography.bodySmall, color: colors.text.secondary, flex: 1, lineHeight: 21 },
  productRow: { minHeight: 64, flexDirection: "row", alignItems: "center", gap: spacing[3], paddingVertical: spacing[2], borderBottomWidth: 1, borderBottomColor: colors.border.default }, productCopy: { flex: 1, minWidth: 0, gap: 2 }, productName: { ...typography.label, color: colors.text.primary }, productMeta: { ...typography.caption, color: colors.text.secondary }, productRight: { minWidth: 76, alignItems: "flex-end", gap: spacing[1] }, productQuantity: { ...typography.label, color: colors.text.primary }, productChange: { ...typography.caption, color: colors.text.muted },
  badge: { alignSelf: "flex-start", paddingHorizontal: spacing[2], paddingVertical: 2, borderRadius: radii.full }, badgeText: { ...typography.caption, fontWeight: "600" }, inlineAction: { minHeight: 40, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing[2], paddingVertical: spacing[1] }, inlineActionText: { ...typography.bodySmall, color: colors.primary[600], fontWeight: "600", flex: 1 },
  categoryRow: { minHeight: 54, flexDirection: "row", alignItems: "center", gap: spacing[3], paddingVertical: spacing[2], borderBottomWidth: 1, borderBottomColor: colors.border.default }, categoryIcon: { width: 36, height: 36, alignItems: "center", justifyContent: "center", borderRadius: radii.full, backgroundColor: colors.primary[50] }, categoryCopy: { flex: 1, gap: 2 }, categoryName: { ...typography.label, color: colors.text.primary }, categoryMeta: { ...typography.caption, color: colors.text.secondary }, categoryValue: { ...typography.label, color: colors.text.primary },
  notice: { padding: spacing[3], borderRadius: radii.md, backgroundColor: colors.primary[50], borderWidth: 1, borderColor: colors.primary[100] }, noticeText: { ...typography.bodySmall, color: colors.primary[800], lineHeight: 20 }, errorText: { ...typography.bodySmall, color: colors.semantic.danger, lineHeight: 20 },
  trendTabs: { flexDirection: "row", gap: spacing[1], paddingBottom: spacing[1] }, trendTab: { minHeight: 38, flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: spacing[1], borderBottomWidth: 2, borderBottomColor: "transparent" }, trendTabActive: { borderBottomColor: colors.primary[600] }, trendTabText: { ...typography.caption, color: colors.text.secondary, textAlign: "center" }, trendTabTextActive: { color: colors.primary[600], fontWeight: "600" },
  legend: { flexDirection: "row", alignItems: "center", gap: spacing[4] }, legendItem: { flexDirection: "row", alignItems: "center", gap: spacing[1] }, legendDot: { width: 8, height: 8, borderRadius: radii.full }, legendText: { ...typography.caption, color: colors.text.secondary }, barRow: { minHeight: 44, flexDirection: "row", alignItems: "center", gap: spacing[2] }, monthLabel: { width: 34, ...typography.caption, color: colors.text.secondary }, barColumn: { flex: 1, gap: 3 }, barLine: { flexDirection: "row", alignItems: "center", gap: spacing[2] }, barTrack: { height: 7, flex: 1, borderRadius: radii.full, backgroundColor: colors.background.subtle, overflow: "hidden" }, barIn: { height: "100%", borderRadius: radii.full, backgroundColor: colors.primary[500] }, barOut: { height: "100%", borderRadius: radii.full, backgroundColor: colors.semantic.danger }, barValue: { width: 34, ...typography.caption, color: colors.text.secondary, textAlign: "right" },
  monthlyHeader: { flexDirection: "row", alignItems: "center", gap: spacing[1] }, monthlyHeaderText: { width: 66, ...typography.caption, color: colors.text.muted }, monthlyHeaderValue: { width: 56, ...typography.caption, color: colors.text.muted, textAlign: "right" }, monthlyRow: { minHeight: 44, flexDirection: "row", alignItems: "center", gap: spacing[1], borderBottomWidth: 1, borderBottomColor: colors.border.default }, monthlyName: { width: 66, ...typography.caption, color: colors.text.primary }, monthlyValue: { width: 56, ...typography.caption, color: colors.text.secondary, textAlign: "right" }, healthHeader: { flexDirection: "row", justifyContent: "flex-end", gap: spacing[2] }, healthHeaderText: { width: 46, ...typography.caption, textAlign: "right", color: colors.text.muted }, healthRow: { minHeight: 42, flexDirection: "row", alignItems: "center", gap: spacing[2], borderBottomWidth: 1, borderBottomColor: colors.border.default }, healthMonth: { flex: 1, ...typography.caption, color: colors.text.primary }, healthValue: { width: 46, ...typography.caption, color: colors.text.secondary, textAlign: "right" },
  chartGrid: { flexDirection: "row", gap: spacing[3] }, chartPanel: { flex: 1, minWidth: 0, alignItems: "center", gap: spacing[2] }, chartTitle: { ...typography.label, color: colors.text.primary }, donutWrap: { width: 122, height: 122, alignItems: "center", justifyContent: "center" }, donutCenter: { position: "absolute", alignItems: "center", justifyContent: "center" }, donutValue: { ...typography.h3, color: colors.text.primary }, donutLabel: { ...typography.caption, color: colors.text.muted }, chartLegend: { width: "100%", gap: spacing[1] }, chartLegendRow: { flexDirection: "row", alignItems: "center", gap: spacing[1] }, chartLegendDot: { width: 8, height: 8, borderRadius: radii.full }, chartLegendLabel: { ...typography.caption, color: colors.text.secondary, flex: 1 }, chartLegendValue: { ...typography.caption, color: colors.text.primary, fontWeight: "600" }, chartXAxis: { flexDirection: "row", gap: spacing[1] }, chartAxisLabel: { flex: 1, ...typography.caption, color: colors.text.muted, textAlign: "center" }, revenueValue: { fontSize: 32, lineHeight: 38, fontWeight: "700", color: colors.text.primary }, revenueMeta: { ...typography.bodySmall, color: colors.text.secondary }, revenueChange: { ...typography.label, fontWeight: "600" }, revenuePeak: { ...typography.caption, color: colors.text.muted },
  emptyTitle: { ...typography.title, color: colors.text.primary, textAlign: "center" }, emptyCopy: { ...typography.bodySmall, color: colors.text.secondary, textAlign: "center", lineHeight: 21 }, emptyWrap: { alignItems: "center", gap: spacing[2], paddingVertical: spacing[5], paddingHorizontal: spacing[3] }, loadPlaceholder: { height: 84, borderRadius: radii.lg, backgroundColor: colors.background.subtle },
  reportRow: { minHeight: 68, flexDirection: "row", alignItems: "center", gap: spacing[3], paddingVertical: spacing[2], borderBottomWidth: 1, borderBottomColor: colors.border.default }, reportIcon: { width: 38, height: 38, alignItems: "center", justifyContent: "center", borderRadius: radii.md, backgroundColor: colors.primary[50] }, reportCopy: { flex: 1, gap: 2 }, reportTitle: { ...typography.label, color: colors.text.primary }, reportDescription: { ...typography.caption, color: colors.text.secondary }, reportTimestamp: { ...typography.caption, color: colors.text.muted },
});

export type InsightsStyles = ReturnType<typeof createInsightsStyles>;
