import { StyleSheet } from "react-native";

import { control, radii, spacing, typography } from "@/theme";
import type { ThemeColors } from "@/theme/tokens";

export const createSettingsStyles = (colors: ThemeColors) => StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background.app },
  screen: { flex: 1 },
  scroll: { flex: 1 },
  content: {
    flexGrow: 1,
    gap: spacing[5],
    width: "100%",
    maxWidth: 700,
    alignSelf: "center",
    paddingHorizontal: spacing[4],
    paddingTop: spacing[4],
    paddingBottom: spacing[8],
  },
  homeContent: { gap: spacing[4], paddingBottom: spacing[6] },
  header: { gap: spacing[1], marginBottom: spacing[1] },
  headerRow: { minHeight: control.lg, flexDirection: "row", alignItems: "center", gap: spacing[2] },
  backButton: { marginLeft: -spacing[2] },
  pageTitle: { ...typography.h2, flex: 1, color: colors.text.primary },
  pageSubtitle: { ...typography.bodySmall, color: colors.text.secondary },
  section: { gap: spacing[2] },
  sectionLabel: {
    ...typography.label,
    color: colors.primary[700],
    fontWeight: "600",
    paddingHorizontal: spacing[1],
  },
  group: {
    overflow: "hidden",
    borderWidth: 1,
    borderColor: colors.border.default,
    borderRadius: radii.lg,
    backgroundColor: colors.background.surface,
  },
  row: {
    minHeight: 62,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
  },
  rowPressed: { opacity: 0.68 },
  iconSlot: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.full,
    backgroundColor: colors.primary[50],
  },
  rowCopy: { minWidth: 0, flex: 1, gap: spacing[1] },
  rowTitle: { ...typography.title, color: colors.text.primary },
  destructiveRowTitle: { color: colors.semantic.danger },
  rowDescription: { ...typography.bodySmall, color: colors.text.secondary },
  rowTrailing: { flexDirection: "row", alignItems: "center", gap: spacing[2], maxWidth: "44%" },
  rowBadge: {
    ...typography.caption,
    paddingHorizontal: spacing[2],
    paddingVertical: spacing[1],
    borderRadius: radii.full,
    color: colors.text.onAccent,
    backgroundColor: colors.accentSoft,
    fontWeight: "600",
  },
  separator: { height: 1, marginLeft: 58, backgroundColor: colors.border.default },
  infoNote: {
    gap: spacing[1],
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[3],
    borderWidth: 1,
    borderColor: colors.border.default,
    borderRadius: radii.md,
    backgroundColor: colors.primary[50],
  },
  infoText: { ...typography.bodySmall, color: colors.text.secondary },
  form: { gap: spacing[4] },
  error: { ...typography.caption, color: colors.semantic.danger },
  radioRow: {
    minHeight: control.lg + spacing[2],
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    paddingHorizontal: spacing[3],
  },
  radio: {
    width: 22,
    height: 22,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border.strong,
    borderRadius: radii.full,
  },
  radioSelected: { borderColor: colors.primary[500], backgroundColor: colors.primary[50] },
  radioLabel: { ...typography.body, flex: 1, color: colors.text.primary },
  radioDescription: { ...typography.bodySmall, color: colors.text.secondary },
  choiceCopy: { flex: 1, gap: 1 },
  statusCard: {
    alignItems: "center",
    gap: spacing[2],
    padding: spacing[5],
    borderWidth: 1,
    borderColor: colors.border.default,
    borderRadius: radii.lg,
    backgroundColor: colors.background.surface,
  },
  statusTitle: { ...typography.h3, color: colors.text.primary, textAlign: "center" },
  statusCopy: { ...typography.bodySmall, color: colors.text.secondary, textAlign: "center" },
  premiumBadge: {
    ...typography.label,
    color: colors.text.onAccent,
    backgroundColor: colors.accentSoft,
    borderRadius: radii.full,
    paddingHorizontal: spacing[2],
    paddingVertical: spacing[1],
    fontWeight: "600",
  },
  filename: { ...typography.label, color: colors.text.primary, textAlign: "center" },
  busyRow: { minHeight: control.lg, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: spacing[2] },
  busyText: { ...typography.bodySmall, color: colors.text.secondary },
  summaryRow: { flexDirection: "row", justifyContent: "space-between", gap: spacing[3] },
  summaryLabel: { ...typography.bodySmall, color: colors.text.secondary },
  summaryValue: { ...typography.label, color: colors.text.primary },
  overlay: { flex: 1, justifyContent: "center", padding: spacing[5], backgroundColor: colors.overlay },
  dialog: {
    width: "100%",
    maxWidth: 420,
    alignSelf: "center",
    gap: spacing[3],
    padding: spacing[5],
    borderRadius: radii.xl,
    backgroundColor: colors.background.surface,
  },
  dialogTitle: { ...typography.h3, color: colors.text.primary },
  dialogCopy: { ...typography.bodySmall, color: colors.text.secondary },
  warningNote: {
    gap: spacing[1],
    padding: spacing[3],
    borderWidth: 1,
    borderColor: colors.semantic.warning,
    borderRadius: radii.md,
    backgroundColor: colors.semantic.warningBackground,
  },
  warningTitle: { ...typography.label, color: colors.semantic.warning },
  warningText: { ...typography.bodySmall, color: colors.text.secondary },
  dialogActions: { flexDirection: "row", gap: spacing[2], marginTop: spacing[1] },
  dialogButton: { minWidth: 0, flex: 1 },
  brandMark: { width: 62, height: 62, alignItems: "center", justifyContent: "center", borderRadius: radii.lg, backgroundColor: colors.primary[50] },
  tagline: { ...typography.label, color: colors.primary[700], textAlign: "center" },
});
