import { StyleSheet } from "react-native";
import { control, radii, spacing, typography } from "@/theme";
import type { ThemeColors } from "@/theme/tokens";

export const createPosStyles = (colors: ThemeColors) => StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background.app }, screen: { flex: 1 }, scroll: { flex: 1 },
  content: { flexGrow: 1, gap: spacing[4], width: "100%", maxWidth: 760, alignSelf: "center", paddingHorizontal: spacing[4], paddingTop: spacing[4], paddingBottom: spacing[8] },
  headerActions: { flexDirection: "row", alignItems: "center", gap: spacing[2] }, moreButton: { width: 44, height: 44 }, transactionIndicator: { ...typography.caption, color: colors.text.secondary }, storeContext: { gap: spacing[1] }, storeContextLabel: { ...typography.caption, color: colors.text.secondary }, storeContextRow: { flexDirection: "row", alignItems: "center", gap: spacing[2] },
  searchField: { minWidth: 0, flex: 1 }, scanButton: { width: control.lg, height: control.lg }, categoryList: { gap: spacing[2], paddingRight: spacing[4] },
  categoryChip: { minHeight: control.sm, alignItems: "center", justifyContent: "center", paddingHorizontal: spacing[3], borderWidth: 1, borderColor: colors.border.default, borderRadius: radii.full, backgroundColor: colors.background.subtle }, categoryChipSelected: { borderColor: colors.primary[600], backgroundColor: colors.primary[50] }, categoryLabel: { ...typography.caption, color: colors.text.secondary, fontWeight: "600" }, categoryLabelSelected: { color: colors.primary[700] },
  error: { ...typography.bodySmall, color: colors.semantic.danger, paddingHorizontal: spacing[1] }, historySection: { gap: spacing[3] }, historyHeader: { flexDirection: "row", alignItems: "center", gap: spacing[2] }, historyHeaderCopy: { flex: 1, gap: spacing[1] }, historyList: { gap: spacing[2] }, historyCard: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing[3], padding: spacing[4], borderWidth: 1, borderColor: colors.border.default, borderRadius: radii.lg, backgroundColor: colors.background.surface }, historyCardCopy: { flex: 1, minWidth: 0, gap: spacing[1] }, historyReceipt: { ...typography.body, color: colors.text.primary, fontWeight: "700" }, historyMeta: { ...typography.caption, color: colors.text.secondary }, historyTotal: { ...typography.body, color: colors.text.primary, fontWeight: "700" }, pressed: { opacity: 0.76 },
  productsSection: { gap: spacing[3] }, sectionHeading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing[3] }, sectionTitle: { ...typography.title, color: colors.text.primary }, sectionMeta: { ...typography.caption, color: colors.text.muted }, productList: { gap: spacing[1] }, productRow: { minHeight: 82, flexDirection: "row", alignItems: "flex-start", gap: spacing[3], paddingVertical: spacing[3], borderBottomWidth: 1, borderBottomColor: colors.border.default, backgroundColor: colors.background.surface }, productCopy: { flex: 1, minWidth: 0, gap: spacing[1], paddingTop: spacing[1] }, productName: { ...typography.body, color: colors.text.primary, fontWeight: "600" }, productAvailability: { ...typography.caption, color: colors.text.secondary }, productMetaRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: spacing[2] }, productIdentifier: { ...typography.caption, color: colors.text.muted }, productAction: { minWidth: 80, alignItems: "flex-end", gap: spacing[2] }, productPrice: { ...typography.title, color: colors.primary[700], fontVariant: ["tabular-nums"] }, addButton: { minWidth: 68, minHeight: control.md }, emptyCard: { alignItems: "center", gap: spacing[2], padding: spacing[6] }, emptyTitle: { ...typography.title, color: colors.text.primary }, emptyCopy: { ...typography.bodySmall, color: colors.text.secondary, textAlign: "center" },
  cart: { gap: spacing[3], padding: spacing[4] }, cartHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, cartTitleRow: { flexDirection: "row", alignItems: "center", gap: spacing[2] }, cartIcon: { width: 36, height: 36, alignItems: "center", justifyContent: "center", borderRadius: radii.md, backgroundColor: colors.primary[50] }, cartItems: { gap: spacing[2] }, emptyCart: { gap: spacing[1], paddingVertical: spacing[2] }, emptyCartTitle: { ...typography.bodySmall, color: colors.text.primary, fontWeight: "600" }, emptyCartCopy: { ...typography.caption, color: colors.text.muted }, cartLine: { gap: spacing[2], paddingVertical: spacing[2], borderBottomWidth: 1, borderBottomColor: colors.border.default }, cartLineTop: { flexDirection: "row", alignItems: "flex-start", gap: spacing[2] }, cartLineCopy: { flex: 1, minWidth: 0 }, cartItemName: { ...typography.bodySmall, color: colors.text.primary, fontWeight: "600" }, cartItemDetail: { ...typography.caption, color: colors.text.secondary }, cartLineActions: { flexDirection: "row", alignItems: "center", gap: spacing[1] }, quantityButton: { width: 40, height: 40, borderColor: colors.primary[200], backgroundColor: colors.primary[50] }, cartQuantity: { minWidth: 32, ...typography.label, color: colors.text.primary, textAlign: "center", fontVariant: ["tabular-nums"] }, cartLineTotal: { minWidth: 76, ...typography.bodySmall, color: colors.text.primary, textAlign: "right", fontWeight: "700", fontVariant: ["tabular-nums"] }, removeButton: { marginLeft: "auto" }, totals: { gap: spacing[2], paddingTop: spacing[2] }, totalRow: { flexDirection: "row", justifyContent: "space-between", gap: spacing[3] }, totalLabel: { ...typography.bodySmall, color: colors.text.secondary }, totalValue: { ...typography.bodySmall, color: colors.text.primary, fontVariant: ["tabular-nums"] }, totalTitle: { ...typography.h3, color: colors.primary[700], fontVariant: ["tabular-nums"] }, checkoutButton: { width: "100%" },
  receiptHeader: { minHeight: control.lg, flexDirection: "row", alignItems: "center", gap: spacing[2], paddingHorizontal: spacing[4], borderBottomWidth: 1, borderBottomColor: colors.border.default, backgroundColor: colors.background.surface }, receiptTitle: { ...typography.h3, color: colors.text.primary }, receiptContent: { width: "100%", maxWidth: 560, alignSelf: "center", gap: spacing[4], padding: spacing[4], paddingBottom: spacing[8] }, receiptCard: { alignItems: "center", gap: spacing[2], padding: spacing[5] }, receiptSuccess: { ...typography.h3, color: colors.text.primary }, receiptBusiness: { ...typography.title, color: colors.text.primary, marginTop: spacing[2] }, receiptStore: { ...typography.bodySmall, color: colors.text.secondary }, receiptMeta: { ...typography.caption, color: colors.text.secondary, textAlign: "center" }, receiptRule: { width: "100%", borderTopWidth: 1, borderTopColor: colors.border.default, marginVertical: spacing[3] }, receiptLine: { width: "100%", flexDirection: "row", justifyContent: "space-between", gap: spacing[3], paddingVertical: spacing[2] }, receiptLineCopy: { flex: 1, minWidth: 0 }, receiptItemName: { ...typography.bodySmall, color: colors.text.primary, fontWeight: "600" }, receiptLineTotal: { ...typography.bodySmall, color: colors.text.primary, fontWeight: "700" }, thankYou: { ...typography.bodySmall, color: colors.text.secondary, marginTop: spacing[4] }, receiptActions: { gap: spacing[2] },
});

export type PosStyles = ReturnType<typeof createPosStyles>;
