import { StyleSheet } from "react-native";
import { radii, spacing, typography, type ThemeColors } from "@/theme";

export const createSheetStyles = (colors: ThemeColors) => StyleSheet.create({
  root: { flex: 1, justifyContent: "flex-end" },
  backdrop: { ...StyleSheet.absoluteFill, backgroundColor: "rgba(36, 28, 23, 0.38)" },
  sheet: { maxHeight: "88%", paddingHorizontal: spacing[5], paddingTop: spacing[3], paddingBottom: spacing[6], gap: spacing[4], borderTopLeftRadius: 24, borderTopRightRadius: 24, borderWidth: 1, borderColor: colors.border.default, backgroundColor: colors.background.surface },
  handle: { width: 36, height: 4, borderRadius: radii.full, backgroundColor: colors.border.strong, alignSelf: "center" },
  sheetHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing[3] },
  title: { ...typography.h3, color: colors.text.primary },
  close: { marginRight: -spacing[2] },
  scroll: { flexGrow: 0 },
  option: { minHeight: 48, paddingHorizontal: spacing[3], flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderRadius: radii.md },
  optionSelected: { backgroundColor: colors.primary[50] },
  optionText: { ...typography.body, color: colors.text.primary },
  optionTextSelected: { color: colors.primary[700], fontWeight: "600" },
  divider: { height: 1, backgroundColor: colors.border.default },
  fieldLabel: { ...typography.label, color: colors.text.primary },
  fields: { flexDirection: "row", gap: spacing[3] },
  field: { flex: 1, gap: spacing[1] },
  input: { minHeight: 48, paddingHorizontal: spacing[3], borderRadius: radii.md, borderWidth: 1, borderColor: colors.border.default, color: colors.text.primary, backgroundColor: colors.background.surface, ...typography.bodySmall },
  error: { ...typography.caption, color: colors.semantic.danger },
  actionRow: { minHeight: 52, flexDirection: "row", alignItems: "center", gap: spacing[3], paddingHorizontal: spacing[2], borderRadius: radii.md },
  actionIcon: { width: 36, height: 36, alignItems: "center", justifyContent: "center", borderRadius: radii.full, backgroundColor: colors.primary[50] },
  actionText: { ...typography.body, color: colors.text.primary, flex: 1 },
  productHeader: { gap: spacing[1] },
  productTitle: { ...typography.h2, color: colors.text.primary },
  meta: { ...typography.bodySmall, color: colors.text.secondary },
  summaryGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing[2] },
  summaryTile: { width: "47%", minHeight: 78, padding: spacing[3], gap: spacing[1], borderRadius: radii.md, backgroundColor: colors.background.subtle },
  summaryLabel: { ...typography.caption, color: colors.text.secondary },
  summaryValue: { ...typography.title, color: colors.text.primary },
  statusPill: { alignSelf: "flex-start", paddingHorizontal: spacing[2], paddingVertical: spacing[1], borderRadius: radii.full },
  statusText: { ...typography.caption, fontWeight: "600" },
  explanation: { ...typography.bodySmall, color: colors.text.secondary, lineHeight: 21 },
  buttonRow: { flexDirection: "row", gap: spacing[2] },
  button: { flex: 1 },
  categoryMetricRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: spacing[2], borderBottomWidth: 1, borderBottomColor: colors.border.default },
  categoryMetricLabel: { ...typography.bodySmall, color: colors.text.secondary },
  categoryMetricValue: { ...typography.label, color: colors.text.primary },
  chartLegend: { flexDirection: "row", alignItems: "center", gap: spacing[3] },
  legendItem: { flexDirection: "row", alignItems: "center", gap: spacing[1] },
  legendDot: { width: 8, height: 8, borderRadius: radii.full },
  legendText: { ...typography.caption, color: colors.text.secondary },
  chartRow: { flexDirection: "row", alignItems: "center", gap: spacing[2], minHeight: 24 },
  chartLabel: { width: 35, ...typography.caption, color: colors.text.secondary },
  chartBars: { flex: 1, gap: spacing[1] },
  chartTrack: { height: 5, borderRadius: radii.full, backgroundColor: colors.background.subtle, overflow: "hidden" },
  chartBarIn: { height: "100%", borderRadius: radii.full, backgroundColor: colors.primary[500] },
  chartBarOut: { height: "100%", borderRadius: radii.full, backgroundColor: colors.semantic.danger },
  reportHeading: { ...typography.title, color: colors.text.primary },
  reportPeriod: { ...typography.bodySmall, color: colors.text.secondary },
  reportTimestamp: { ...typography.caption, color: colors.text.muted },
});

export type SheetStyles = ReturnType<typeof createSheetStyles>;
